import React from "react";
import { siteConfig } from "@/config/site";
import { Navigation } from "@/components/landing/Navigation";
import { LandingFooter } from "@/components/landing/LandingFooter";
import { FileText } from "lucide-react";

export default function TermsOfServicePage() {
  return (
    <main className="min-h-screen bg-slate-50 font-sans text-slate-900">
      <Navigation />
      <div className="max-w-4xl mx-auto px-6 py-32 lg:px-8">
        <div className="flex items-center gap-4 mb-8">
          <div className="p-3 bg-purple-100 text-purple-600 rounded-2xl">
            <FileText className="w-8 h-8" />
          </div>
          <h1 className="text-4xl font-extrabold tracking-tight">Terms of Service</h1>
        </div>
        
        <div className="prose prose-slate max-w-none prose-headings:font-bold prose-headings:tracking-tight bg-white p-8 md:p-12 rounded-3xl shadow-sm border border-slate-200">
          <p className="lead text-lg text-slate-600">Last updated: {new Date().toLocaleDateString()}</p>
          
          <h2>1. Nature of Service</h2>
          <p>{siteConfig.name} is a travel planning and price comparison tool. <strong>We are an affiliate and referral layer, not the merchant of record.</strong> All actual bookings and payments are processed directly through our third-party travel partners (such as airlines, hotels, or booking agencies).</p>

          <h2>2. Pricing Accuracy Disclaimer</h2>
          <p>Prices shown on our platform are estimates pulled from various providers. Final prices, availability, and applicable taxes or fees may change at checkout on the provider's website. Always verify pricing and availability directly with the provider before making a purchase.</p>

          <div className="bg-amber-50 p-6 rounded-xl border border-amber-200 my-6 text-amber-900">
            <h3 className="text-amber-800 mt-0">AI-Generated Content Disclaimer</h3>
            <p className="mb-0">Itineraries, prices, and recommendations generated by {siteConfig.name}'s AI planner are provided for informational purposes and may contain errors or outdated information. Always verify pricing, availability, and booking details directly with the relevant provider before making a purchase. {siteConfig.name} is not liable for discrepancies between AI-generated estimates and actual prices or availability.</p>
          </div>

          <h2>3. Limitation of Liability</h2>
          <p>Because we do not process bookings directly, {siteConfig.name} holds no liability for third-party provider failures. This includes, but is not limited to, airline delays, cancellations, hotel overbookings, or payment disputes. All such issues must be resolved directly with the booking provider.</p>

          <h2>4. User Responsibilities</h2>
          <p>Users are responsible for ensuring the accuracy of their travel information (names, passport details, dates) when completing bookings on third-party sites. Users are also responsible for securing appropriate travel visas and insurance.</p>

          <h2>5. Dispute Resolution & Governing Law</h2>
          <p>These terms shall be governed by and construed in accordance with the laws of India. Any disputes arising out of these terms will be subject to the exclusive jurisdiction of the courts located in Maharashtra, India.</p>
        </div>
      </div>
      <LandingFooter />
    </main>
  );
}
